### ISSUE TITLE
BlocksForward not working

### ISSUE THREAD

**Issue by mallickrishg** [jploveless/Blocks#1]
Hi,
I am using the most recent version of Blocks from this repository, and it seems like the BlocksForward problem is not working. I get this error.

In an assignment  A(:) = B, the number of elements in A and B must be the same.

Error in BlockLabel (line 218)
    stl(stl == 0) = ext;

Error in BlocksForward (line 41)
[Segment, Block, Station]                        = BlockLabel(Segment, Block, Station);

Error in visualize_fwd_blocks (line 11)
V=BlocksForward(EE,NN,outdir);

However, I checked with the version of Blocks in brendanjmeade's repository and that seems to be working fine. Can you help me figure out what is wrong?

Thanks,
Rishav

**Comment by jploveless** [comment]
Dear Rishav,

This is an issue with assigning labels to the calculation points EE and NN.
I cannot reproduce the error with one of my results directories. Could you
create a .zip file of your results directory (i.e., 0000000001/) and send
it to me, along with a .mat file with your EE and NN variables so that I
could debug this issue?

Many thanks and best regards,
Jack

--
Jack Loveless
Associate Professor, Department of Geosciences
Smith College
44 College Lane
Northampton, MA 01063, USA
(413) 585-2657
http://www.science.smith.edu/jloveless
